spring:
  cloud:
    kubernetes:
      client:
        namespace: project-2
  application:
    name: helloboot

simplecalculator:
  ribbon:
    eureka:
      enabled: false
    client:
      enabled: true
    ServerListRefreshInterval: 5000